name       : xorg-driver-video-sis
version    : 0.11.0
release    : 7
source     :
    - https://gitlab.freedesktop.org/xorg/driver/xf86-video-sis/-/archive/xf86-video-sis-0.11.0/xf86-video-sis-xf86-video-sis-0.11.0.tar.bz2 : c1fc0f90e173687bfd76e15089f46f134762fafb4d51b5ace302ac7335e1e987
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : SiS Video Driver
description: |
    The Xorg SiS Driver package contains the X.Org Video Driver for SiS (Silicon Integrated Systems) and XGI video cards including SiS5597/5598, SiS530/620, SiS6326/AGP/DVD, SiS300/305, SiS540, SiS630/730, SiS315/E/H/PRO, SiS550/551/552, SiS650/651/661/741, SiS330 (Xabre), SiS760/761, XGI Volari V3/V5/V8 and XGI Volari Z7 chipsets.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
